[uncaught] Traceback (most recent call last):
[uncaught]   File "/storage/homefs/bj20p045/DDLS/Fine-Tuning-Personalization-in-Federated-Learning-to-Mitigate-Adversarial-Clients/main_dist.py", line 134, in <module>
[uncaught]     os.mkdir(dataset_folder)
[uncaught] FileNotFoundError: [Errno 2] No such file or directory: './experiments_distribution/mnist'
[uncaught] Traceback (most recent call last):
[uncaught]   File "/storage/homefs/bj20p045/DDLS/Fine-Tuning-Personalization-in-Federated-Learning-to-Mitigate-Adversarial-Clients/main_dist.py", line 134, in <module>
[uncaught]     os.mkdir(dataset_folder)
[uncaught] FileNotFoundError: [Errno 2] No such file or directory: './experiments_distribution/mnist'
[uncaught] Traceback (most recent call last):
[uncaught]   File "/storage/homefs/bj20p045/DDLS/Fine-Tuning-Personalization-in-Federated-Learning-to-Mitigate-Adversarial-Clients/main_dist.py", line 134, in <module>
[uncaught]     os.mkdir(dataset_folder)
[uncaught] FileNotFoundError: [Errno 2] No such file or directory: './experiments_distribution/mnist'
[uncaught] Traceback (most recent call last):
[uncaught]   File "/storage/homefs/bj20p045/DDLS/Fine-Tuning-Personalization-in-Federated-Learning-to-Mitigate-Adversarial-Clients/main_dist.py", line 134, in <module>
[uncaught]     os.mkdir(dataset_folder)
[uncaught] FileNotFoundError: [Errno 2] No such file or directory: './experiments_distribution/mnist'
[uncaught] Traceback (most recent call last):
[uncaught]   File "/storage/homefs/bj20p045/DDLS/Fine-Tuning-Personalization-in-Federated-Learning-to-Mitigate-Adversarial-Clients/main_dist.py", line 134, in <module>
[uncaught]     os.mkdir(dataset_folder)
[uncaught] FileNotFoundError: [Errno 2] No such file or directory: './experiments_distribution/mnist'
[uncaught] Traceback (most recent call last):
[uncaught]   File "/storage/homefs/bj20p045/DDLS/Fine-Tuning-Personalization-in-Federated-Learning-to-Mitigate-Adversarial-Clients/main_dist.py", line 134, in <module>
[uncaught]     os.mkdir(dataset_folder)
[uncaught] FileNotFoundError: [Errno 2] No such file or directory: './experiments_distribution/mnist'
[uncaught] Traceback (most recent call last):
[uncaught]   File "/storage/homefs/bj20p045/DDLS/Fine-Tuning-Personalization-in-Federated-Learning-to-Mitigate-Adversarial-Clients/main_dist.py", line 134, in <module>
[uncaught]     os.mkdir(dataset_folder)
[uncaught] FileNotFoundError: [Errno 2] No such file or directory: './experiments_distribution/mnist'
[uncaught] Traceback (most recent call last):
[uncaught]   File "/storage/homefs/bj20p045/DDLS/Fine-Tuning-Personalization-in-Federated-Learning-to-Mitigate-Adversarial-Clients/main_dist.py", line 134, in <module>
[uncaught]     os.mkdir(dataset_folder)
[uncaught] FileNotFoundError: [Errno 2] No such file or directory: './experiments_distribution/mnist'
